import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import ToasterContext from "./context/ToasterContext.jsx";
import { League_Spartan } from "next/font/google";
import NavBar from "./components/NavBar.jsx";

const league_spartan = League_Spartan({
  subsets: ["latin"],
  variable: "--font-league_spartan"
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" className={`h-full ${league_spartan.variable}` }>
        <body className="h-full">
          <ToasterContext />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
